### PR TITLE
Update docs for users

### PR DESCRIPTION
**Pull request by nick-statsig**

### CODE REVIEW

**Comment by jasonwzm** [comment]
🚀 Deployed on https://65c3c3dd8c3d8a007a4c3790--cozy-fox-0defec.netlify.app

**Review by jacob-statsig — CHANGES_REQUESTED** [review]
Can we "save without formatting"
Spotlight API the website we use for editting these docs (at the moment) requires the JSON to be a specific format.

**Comment by jacob-statsig** [comment]
Also could you throw in a screen shot of the new docs page rendered with your changes

**Comment by nick-statsig** [comment]
Screenshot 2024-02-07 at 9 22 53 AM

**Pull request merged**
