### PR TITLE
[SCIM] Updated Org Role Images

### PR DESCRIPTION
**Pull request by jairo-statsig**
## Changes
- Add more images as guides to help with org role setup

### CODE REVIEW

**Comment by jairo-statsig** [comment]
* **#2255** <a href="https://app.graphite.dev/github/pr/statsig-io/docs/2255?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jairo-statsig and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jasonwzm** [comment]
🚀 Deployed on https://67217e5aa73136bf28f28e40--cozy-fox-0defec.netlify.app

**Review by anle-statsig — APPROVED** [review]
lgtm

**Comment by jairo-statsig** [comment]
### Merge activity

* **Oct 29, 8:43 PM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/statsig-io/docs/2255).

**Pull request merged**
