### PR TITLE
[SCIM] Mention Import Groups flag Setting

### PR DESCRIPTION
**Pull request by jairo-statsig**

### CODE REVIEW

**Comment by jairo-statsig** [comment]
* **#2277** <a href="https://app.graphite.dev/github/pr/statsig-io/docs/2277?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jairo-statsig and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jasonwzm** [comment]
🚀 Deployed on https://6725494992df75514a2d3a83--cozy-fox-0defec.netlify.app

**Review by anle-statsig — APPROVED** [review]
lgtm

**Comment by anle-statsig** [comment]
### Merge activity

* **Nov 1, 6:17 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/statsig-io/docs/2277).

**Pull request merged**
