### PR TITLE
Move the keys js to json

### PR DESCRIPTION
**Pull request by anle-statsig**
Still work as expected

### CODE REVIEW

**Comment by anle-statsig** [comment]
* **#1598** <a href="https://app.graphite.dev/github/pr/statsig-io/docs/1598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @anle-statsig and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jasonwzm** [comment]
🚀 Deployed on https://664be76ada79e853abb9622e--cozy-fox-0defec.netlify.app

**Review by jairo-statsig — APPROVED** [review]

**Comment by jairo-statsig** [comment]
Added via Giphy

**Comment by anle-statsig** [comment]
### Merge activity

* **May 22, 6:49 PM EDT**: @anle-statsig started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/statsig-io/docs/1598).

**Pull request merged**
