### PR TITLE
add schema doc

### PR DESCRIPTION
**Pull request by brian-statsig**

### CODE REVIEW

**Comment by brian-statsig** [comment]
* **#1839** <a href="https://app.graphite.dev/github/pr/statsig-io/docs/1839?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @brian-statsig and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jasonwzm** [comment]
🚀 Deployed on https://66a7c624bbc01e3ad72aaa26--cozy-fox-0defec.netlify.app

**Review by vmadhusudanan — CHANGES_REQUESTED** [review]
LGTM. Add a line saying this is only enforced at edit time.

**Comment by brian-statsig** [comment]
### Merge activity

* **Jul 29, 1:41 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/statsig-io/docs/1839) rebased this pull request as part of a merge.

**Pull request merged**
