### PR TITLE
Add Hightouch integration docs

### PR DESCRIPTION
**Pull request by Meschreiber**
Hey there!

I’m a docs manager at [Hightouch](https://hightouch.com/), a reverse ETL platform. We’d love to add some documentation about the [Statsig destination](https://hightouch.com/docs/destinations/statsig) we just built. Hopefully directly submitting a PR is the right way to go about this, but please let me know if there’s any other steps to take.

### CODE REVIEW

**Comment by kenny-statsig** [comment]
Hey there! I made some minor changes to your PR over here https://github.com/statsig-io/docs/pull/758.
Thanks for building this integration. I'd love to try it out! Do you have a demo account I can use?

**Comment by Meschreiber** [comment]
Awesome, thanks so much @kenny-statsig , looks great.

Re: trial, we don't have official demo account AFAIK, just encourage folks to get on a free account. LMK if that doesn't work for some reason, and I can see if we can set something up.

And thanks for the call out re: rate limits, will definitely add!

**Comment by Meschreiber** [comment]
> default rate limit of 10 req/s and 4500 req/15min on Console API

Hey @kenny-statsig , just wanted to double check on the rate limit piece: you mention the default values--is there a way to change them?

**Comment by kenny-statsig** [comment]
> > default rate limit of 10 req/s and 4500 req/15min on Console API
> 
> Hey @kenny-statsig , just wanted to double check on the rate limit piece: you mention the default values--is there a way to change them? Was looking in the [Console API docs](https://docs.statsig.com/console-api/introduction) and might've missed it

These are rate limits that we set internally. The only way to change them is to upgrade to an enterprise account.

**Comment by kenny-statsig** [comment]
Committed

**Pull request closed without merging**
