### PR TITLE
New DWH Flow for Docs

### PR DESCRIPTION
**Pull request by andy-statsig**
- Re-organized folder structure for data ingestion.
- Moved old pages to 'Other' folder and marked them with (deprecated).
- Added clarifying images to "Connection Set Up" and each categories of DWH.
- Moved and consolidated data mapping into subcategory.

### CODE REVIEW

**Comment by jasonwzm** [comment]
🚀 Deployed on https://630e73d24b3c9d0cefa9ef41--cozy-fox-0defec.netlify.app

**Comment by andy-statsig** [comment]
Waiting until team reviews to merge

**Comment by craig-statsig** [comment]
1.) Should we put these in a top level folder for "Data Warehouse Ingestion" instead of under "Integrations"? This would reflect the structure in product and differentiate it from the other kind of integrations/webhooks
2.) Should we add a "high level overview" to the overview tab of what they'll do? I sort of did this but I think for a new user it might be a little confusing (e.g. we can link to the setup page, etc.) and say "give us credentials, write a query, map the query, schedule)

**Review by craig-statsig — APPROVED** [review]
approve 2 unblock

**Pull request merged**
