### PR TITLE
Fix like like

### PR DESCRIPTION
**Pull request by craig-statsig**

### CODE REVIEW

**Comment by craig-statsig** [comment]
* **#1660** <a href="https://app.graphite.dev/github/pr/statsig-io/docs/1660?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @craig-statsig and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by danielwest-statsig — APPROVED** [review]

**Comment by jasonwzm** [comment]
🚀 Deployed on https://666a33bb4ac3e656bdb72d3e--cozy-fox-0defec.netlify.app

**Comment by craig-statsig** [comment]
### Merge activity

* **Jun 12, 7:50 PM EDT**: @craig-statsig merged this pull request with [Graphite](https://app.graphite.dev/github/pr/statsig-io/docs/1660).

**Comment by danielwest-statsig** [comment]
even with extensive research this one is still completely over my head...

**Pull request merged**
